"""
Valid values extracted from the trained LightGBM model.
Used for input validation so the model only receives known categories.
"""

VALID_SPECIES = [
    "Achromobacter insolitus",
    "Achromobacter xylosoxidans",
    "Acidaminococcus fermentans",
    "Acinetobacter alcaligenes",
    "Acinetobacter anitratus",
    "Acinetobacter baumannii",
    "Acinetobacter baylyi",
    "Acinetobacter beijerinckii",
    "Acinetobacter bereziniae",
    "Acinetobacter calcoaceticus",
    "Acinetobacter colistiniresistens",
    "Acinetobacter courvalinii",
    "Acinetobacter dijkshoorniae",
    "Acinetobacter dispersus",
    "Acinetobacter guillouiae",
]
# NOTE: The full species list has 362 entries. We'll load it from the model at runtime instead.

VALID_FAMILY = [
    "Enterobacterales",
    "Enterobacteriaceae",
    "Enterococcus spp",
    "Gram Negative Anaerobes",
    "Gram Positive Anaerobes",
    "Haemophilus spp",
    "Neisseria gonorrhoeae",
    "Non-Enterobacterales",
    "Non-Enterobacteriaceae",
    "Staphylococcus spp",
    "Streptococcus pneumoniae",
    "Streptococcus spp (no S. pneumo)",
]

VALID_COUNTRY = [
    "Argentina",
    "Australia",
    "Austria",
    "Belgium",
    "Brazil",
    "Bulgaria",
    "Cameroon",
    "Canada",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Croatia",
    "Czech Republic",
    "Denmark",
    "Dominican Republic",
    "Egypt",
    "El Salvador",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Ghana",
    "Greece",
    "Guatemala",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "India",
    "Indonesia",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kenya",
    "Korea, South",
    "Kuwait",
    "Latvia",
    "Lebanon",
    "Lithuania",
    "Malawi",
    "Malaysia",
    "Mauritius",
    "Mexico",
    "Morocco",
    "Namibia",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Panama",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Saudi Arabia",
    "Serbia",
    "Singapore",
    "Slovak Republic",
    "Slovenia",
    "South Africa",
    "Spain",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Thailand",
    "Tunisia",
    "Turkey",
    "Uganda",
    "Ukraine",
    "United Kingdom",
    "United States",
    "Venezuela",
    "Vietnam",
]

VALID_AGE_GROUP = [
    "0 to 2 Years",
    "3 to 12 Years",
    "13 to 18 Years",
    "19 to 64 Years",
    "65 to 84 Years",
    "85 and Over",
    "Unknown",
]

VALID_SOURCE = [
    "Abdominal Fluid",
    "Abscess",
    "Appendix",
    "Ascetic Fluid",
    "Aspirate",
    "Bile",
    "Bladder",
    "Blood",
    "Blood Vessels",
    "Bodily Fluids",
    "Bone",
    "Bone Marrow",
    "Brain",
    "Bronchiole",
    "Bronchoalveolar lavage",
    "Bronchus",
    "Burn",
    "CNS: Other",
    "CSF",
    "Carbuncle",
    "Catheters",
    "Cellulitis",
    "Cervix",
    "Circulatory: Other",
    "Colon",
    "Decubitus",
    "Diverticulum",
    "Drains",
    "Ear",
    "Endotracheal aspirate",
    "Esophagus",
    "Exudate",
    "Eye",
    "Fallopian Tubes",
    "Feces/Stool",
    "Furuncle",
    "Gall Bladder",
    "Gastric Abscess",
    "Genitourinary: Other",
    "HEENT: Other",
    "Hair",
    "Head",
    "Heart",
    "Ileum",
    "Impetiginous lesions",
    "Instruments: Other",
    "Integumentary (Skin Nail Hair)",
    "Intestinal: Other",
    "Kidney",
    "Liver",
    "Lungs",
    "Lymph Nodes",
    "Lymphatic Fluid",
    "Mouth",
    "Muscle",
    "Nails",
    "Nasopharyngeal Aspirate",
    "Nasotracheal Aspirate",
    "None Given",
    "Nose",
    "Ovary",
    "Pancreas",
    "Paracentesis Fluid",
    "Penis",
    "Peripheral Nerves",
    "Peritoneal Fluid",
    "Placenta",
    "Pleural Fluid",
    "Prostate",
    "Pyoderma Lesion",
    "Rectum",
    "Respiratory: Other",
    "Respiratory: Sinuses",
    "Skeletal: Other",
    "Skin",
    "Skin: Other",
    "Spinal Cord",
    "Spleen",
    "Sputum",
    "Stomach",
    "Synovial Fluid",
    "Testis",
    "Thoracentesis Fluid",
    "Throat",
    "Thymus",
    "Tissue Fluid",
    "Trachea",
    "Transtracheal Aspirate",
    "Ulcer",
    "Ureter",
    "Urethra",
    "Urine",
    "Uterus",
    "Vagina",
    "Vas Deferens",
    "Vomit",
    "Wound",
]

VALID_PHENOTYPE = ["(BL Neg)", "(BL Pos)", "ESBL", "MRSA", "MSSA", "unknown"]

VALID_DATASET = ["atlas", "eskapee", "who"]

# Year range the model was trained on
MIN_YEAR = 2004
MAX_YEAR = 2025
